In [6]:
!pip install pyodbc

Requirement already satisfied: pyodbc in c:\users\genesis\appdata\local\programs\python\python310\lib\site-packages (5.2.0)

[notice] A new release of pip is available: 23.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.master("local[*]").appName("tutorial").getOrCreate()

In [5]:
from pyspark.sql import SparkSession
import pyodbc

spark = SparkSession.builder \
    .master("local[*]") \
    .appName("Jupyter PySpark") \
    .config("spark.executor.memory", "2g") \
    .config("spark.sql.sources.commitProtocolClass", "org.apache.spark.sql.execution.datasources.SQLHadoopMapReduceCommitProtocol") \
    .config("spark.sql.parquet.output.committer.class", "org.apache.hadoop.mapreduce.lib.output.DirectFileOutputCommitter") \
    .getOrCreate()
conn = pyodbc.connect(
    'DRIVER={ODBC Driver 17 for SQL Server};'
    'SERVER=localhost;'
    'DATABASE=chinook;'
    'Trusted_Connection=yes;'
)
cursor = conn.cursor()

KeyboardInterrupt:

In [2]:

cursor.execute("Select * from Invoice")

NameError: name 'cursor' is not defined

In [23]:
cursor.fetchall()

[(1, 2, datetime.datetime(2021, 1, 1, 0, 0), 'Theodor-Heuss-Straße 34', 'Stuttgart', None, 'Germany', '70174', Decimal('1.98'), 'UPI'),
 (2, 4, datetime.datetime(2021, 1, 2, 0, 0), 'Ullevålsveien 14', 'Oslo', None, 'Norway', '0171', Decimal('3.96'), 'Cash'),
 (3, 8, datetime.datetime(2021, 1, 3, 0, 0), 'Grétrystraat 63', 'Brussels', None, 'Belgium', '1000', Decimal('5.94'), 'Credit Card'),
 (4, 14, datetime.datetime(2021, 1, 6, 0, 0), '8210 111 ST NW', 'Edmonton', 'AB', 'Canada', 'T6G 2C7', Decimal('8.91'), 'UPI'),
 (5, 23, datetime.datetime(2021, 1, 11, 0, 0), '69 Salem Street', 'Boston', 'MA', 'USA', '2113', Decimal('13.86'), 'Cash'),
 (6, 37, datetime.datetime(2021, 1, 19, 0, 0), 'Berger Straße 10', 'Frankfurt', None, 'Germany', '60316', Decimal('0.99'), 'Credit Card'),
 (7, 38, datetime.datetime(2021, 2, 1, 0, 0), 'Barbarossastraße 19', 'Berlin', None, 'Germany', '10779', Decimal('1.98'), 'UPI'),
 (8, 40, datetime.datetime(2021, 2, 1, 0, 0), '8, Rue Hanovre', 'Paris', None, 'France', '75002', Decimal('1.98'), 'Cash'),
 (9, 42, datetime.datetime(2021, 2, 2, 0, 0), '9, Place Louis Barthou', 'Bordeaux', None, 'France', '33000', Decimal('3.96'), 'Credit Card'),
 (10, 46, datetime.datetime(2021, 2, 3, 0, 0), '3 Chatham Street', 'Dublin', 'Dublin', 'Ireland', None, Decimal('5.94'), 'UPI'),
 (11, 52, datetime.datetime(2021, 2, 6, 0, 0), '202 Hoxton Street', 'London', None, 'United Kingdom', 'N1 5LH', Decimal('8.91'), 'Cash'),
 (12, 2, datetime.datetime(2021, 2, 11, 0, 0), 'Theodor-Heuss-Straße 34', 'Stuttgart', None, 'Germany', '70174', Decimal('13.86'), 'Credit Card'),
 (13, 16, datetime.datetime(2021, 2, 19, 0, 0), '1600 Amphitheatre Parkway', 'Mountain View', 'CA', 'USA', '94043-1351', Decimal('0.99'), 'UPI'),
 (14, 17, datetime.datetime(2021, 3, 4, 0, 0), '1 Microsoft Way', 'Redmond', 'WA', 'USA', '98052-8300', Decimal('1.98'), 'Cash'),
 (15, 19, datetime.datetime(2021, 3, 4, 0, 0), '1 Infinite Loop', 'Cupertino', 'CA', 'USA', '95014', Decimal('1.98'), 'Credit Card'),
 (16, 21, datetime.datetime(2021, 3, 5, 0, 0), '801 W 4th Street', 'Reno', 'NV', 'USA', '89503', Decimal('3.96'), 'UPI'),
 (17, 25, datetime.datetime(2021, 3, 6, 0, 0), '319 N. Frances Street', 'Madison', 'WI', 'USA', '53703', Decimal('5.94'), 'Cash'),
 (18, 31, datetime.datetime(2021, 3, 9, 0, 0), '194A Chain Lake Drive', 'Halifax', 'NS', 'Canada', 'B3S 1C5', Decimal('8.91'), 'Credit Card'),
 (19, 40, datetime.datetime(2021, 3, 14, 0, 0), '8, Rue Hanovre', 'Paris', None, 'France', '75002', Decimal('13.86'), 'UPI'),
 (20, 54, datetime.datetime(2021, 3, 22, 0, 0), '110 Raeburn Pl', 'Edinburgh ', None, 'United Kingdom', 'EH4 1HH', Decimal('0.99'), 'Cash'),
 (21, 55, datetime.datetime(2021, 4, 4, 0, 0), '421 Bourke Street', 'Sidney', 'NSW', 'Australia', '2010', Decimal('1.98'), 'Credit Card'),
 (22, 57, datetime.datetime(2021, 4, 4, 0, 0), 'Calle Lira, 198', 'Santiago', None, 'Chile', None, Decimal('1.98'), 'UPI'),
 (23, 59, datetime.datetime(2021, 4, 5, 0, 0), '3,Raj Bhavan Road', 'Bangalore', None, 'India', '560001', Decimal('3.96'), 'Cash'),
 (24, 4, datetime.datetime(2021, 4, 6, 0, 0), 'Ullevålsveien 14', 'Oslo', None, 'Norway', '0171', Decimal('5.94'), 'Credit Card'),
 (25, 10, datetime.datetime(2021, 4, 9, 0, 0), 'Rua Dr. Falcão Filho, 155', 'São Paulo', 'SP', 'Brazil', '01007-010', Decimal('8.91'), 'UPI'),
 (26, 19, datetime.datetime(2021, 4, 14, 0, 0), '1 Infinite Loop', 'Cupertino', 'CA', 'USA', '95014', Decimal('13.86'), 'Cash'),
 (27, 33, datetime.datetime(2021, 4, 22, 0, 0), '5112 48 Street', 'Yellowknife', 'NT', 'Canada', 'X1A 1N6', Decimal('0.99'), 'Credit Card'),
 (28, 34, datetime.datetime(2021, 5, 5, 0, 0), 'Rua da Assunção 53', 'Lisbon', None, 'Portugal', None, Decimal('1.98'), 'UPI'),
 (29, 36, datetime.datetime(2021, 5, 5, 0, 0), 'Tauentzienstraße 8', 'Berlin', None, 'Germany', '10789', Decimal('1.98'), 'Cash'),
 (30, 38, datetime.datetime(2021, 5, 6, 0, 0), 'Barbarossastraße 19', 'Berlin', None, 'Germany', '10779', Decimal('3.96'), 'Credit Card'),
 (31, 42, datetime.datetime(2021, 5, 7, 0, 0), '9, Place Louis Barthou', 'Bordeaux', None, 'France', '33000', Decimal('5.94'), 'UPI'),
 (32, 48, datetime.datetime(2021, 5, 10, 0, 0), 'Lijnbaansgracht 120bg', 'Amsterdam', 'VV', 'Netherlands', '1016', Decimal('8.91'), 'Cash'),
 (33, 57, datetime.datetime(2021, 5, 15, 0, 0), 'Calle Lira, 198', 'Santiago', None, 'Chile', None, Decimal('13.86'), 'Credit Card'),
 (34, 12, datetime.datetime(2021, 5, 23, 0, 0), 'Praça Pio X, 119', 'Rio de Janeiro', 'RJ', 'Brazil', '20040-020', Decimal('0.99'), 'UPI'),
 (35, 13, datetime.datetime(2021, 6, 5, 0, 0), 'Qe 7 Bloco G', 'Brasília', 'DF', 'Brazil', '71020-677', Decimal('1.98'), 'Cash'),
 (36, 15, datetime.datetime(2021, 6, 5, 0, 0), '700 W Pender Street', 'Vancouver', 'BC', 'Canada', 'V6C 1G8', Decimal('1.98'), 'Credit Card'),
 (37, 17, datetime.datetime(2021, 6, 6, 0, 0), '1 Microsoft Way', 'Redmond', 'WA', 'USA', '98052-8300', Decimal('3.96'), 'UPI'),
 (38, 21, datetime.datetime(2021, 6, 7, 0, 0), '801 W 4th Street', 'Reno', 'NV', 'USA', '89503', Decimal('5.94'), 'Cash'),
 (39, 27, datetime.datetime(2021, 6, 10, 0, 0), '1033 N Park Ave', 'Tucson', 'AZ', 'USA', '85719', Decimal('8.91'), 'Credit Card'),
 (40, 36, datetime.datetime(2021, 6, 15, 0, 0), 'Tauentzienstraße 8', 'Berlin', None, 'Germany', '10789', Decimal('13.86'), 'UPI'),
 (41, 50, datetime.datetime(2021, 6, 23, 0, 0), 'C/ San Bernardo 85', 'Madrid', None, 'Spain', '28015', Decimal('0.99'), 'Cash'),
 (42, 51, datetime.datetime(2021, 7, 6, 0, 0), 'Celsiusg. 9', 'Stockholm', None, 'Sweden', '11230', Decimal('1.98'), 'Credit Card'),
 (43, 53, datetime.datetime(2021, 7, 6, 0, 0), '113 Lupus St', 'London', None, 'United Kingdom', 'SW1V 3EN', Decimal('1.98'), 'UPI'),
 (44, 55, datetime.datetime(2021, 7, 7, 0, 0), '421 Bourke Street', 'Sidney', 'NSW', 'Australia', '2010', Decimal('3.96'), 'Cash'),
 (45, 59, datetime.datetime(2021, 7, 8, 0, 0), '3,Raj Bhavan Road', 'Bangalore', None, 'India', '560001', Decimal('5.94'), 'Credit Card'),
 (46, 6, datetime.datetime(2021, 7, 11, 0, 0), 'Rilská 3174/6', 'Prague', None, 'Czech Republic', '14300', Decimal('8.91'), 'UPI'),
 (47, 15, datetime.datetime(2021, 7, 16, 0, 0), '700 W Pender Street', 'Vancouver', 'BC', 'Canada', 'V6C 1G8', Decimal('13.86'), 'Cash'),
 (48, 29, datetime.datetime(2021, 7, 24, 0, 0), '796 Dundas Street West', 'Toronto', 'ON', 'Canada', 'M6J 1V1', Decimal('0.99'), 'Credit Card'),
 (49, 30, datetime.datetime(2021, 8, 6, 0, 0), '230 Elgin Street', 'Ottawa', 'ON', 'Canada', 'K2P 1L7', Decimal('1.98'), 'UPI'),
 (50, 32, datetime.datetime(2021, 8, 6, 0, 0), '696 Osborne Street', 'Winnipeg', 'MB', 'Canada', 'R3L 2B9', Decimal('1.98'), 'Cash'),
 (51, 34, datetime.datetime(2021, 8, 7, 0, 0), 'Rua da Assunção 53', 'Lisbon', None, 'Portugal', None, Decimal('3.96'), 'Credit Card'),
 (52, 38, datetime.datetime(2021, 8, 8, 0, 0), 'Barbarossastraße 19', 'Berlin', None, 'Germany', '10779', Decimal('5.94'), 'UPI'),
 (53, 44, datetime.datetime(2021, 8, 11, 0, 0), 'Porthaninkatu 9', 'Helsinki', None, 'Finland', '00530', Decimal('8.91'), 'Cash'),
 (54, 53, datetime.datetime(2021, 8, 16, 0, 0), '113 Lupus St', 'London', None, 'United Kingdom', 'SW1V 3EN', Decimal('13.86'), 'Credit Card'),
 (55, 8, datetime.datetime(2021, 8, 24, 0, 0), 'Grétrystraat 63', 'Brussels', None, 'Belgium', '1000', Decimal('0.99'), 'UPI'),
 (56, 9, datetime.datetime(2021, 9, 6, 0, 0), 'Sønder Boulevard 51', 'Copenhagen', None, 'Denmark', '1720', Decimal('1.98'), 'Cash'),
 (57, 11, datetime.datetime(2021, 9, 6, 0, 0), 'Av. Paulista, 2022', 'São Paulo', 'SP', 'Brazil', '01310-200', Decimal('1.98'), 'Credit Card'),
 (58, 13, datetime.datetime(2021, 9, 7, 0, 0), 'Qe 7 Bloco G', 'Brasília', 'DF', 'Brazil', '71020-677', Decimal('3.96'), 'UPI'),
 (59, 17, datetime.datetime(2021, 9, 8, 0, 0), '1 Microsoft Way', 'Redmond', 'WA', 'USA', '98052-8300', Decimal('5.94'), 'Cash'),
 (60, 23, datetime.datetime(2021, 9, 11, 0, 0), '69 Salem Street', 'Boston', 'MA', 'USA', '2113', Decimal('8.91'), 'Credit Card'),
 (61, 32, datetime.datetime(2021, 9, 16, 0, 0), '696 Osborne Street', 'Winnipeg', 'MB', 'Canada', 'R3L 2B9', Decimal('13.86'), 'UPI'),
 (62, 46, datetime.datetime(2021, 9, 24, 0, 0), '3 Chatham Street', 'Dublin', 'Dublin', 'Ireland', None, Decimal('0.99'), 'Cash'),
 (63, 47, datetime.datetime(2021, 10, 7, 0, 0), 'Via Degli Scipioni, 43', 'Rome', 'RM', 'Italy', '00192', Decimal('1.98'), 'Credit Card'),
 (64, 49, datetime.datetime(2021, 10, 7, 0, 0), 'Ordynacka 10', 'Warsaw', None, 'Poland', '00-358', Decimal('1.98'), 'UPI'),
 (65, 51, datetime.datetime(2021, 10, 8, 0, 0), 'Celsiusg. 9', 'Stockholm', None, 'Sweden', '11230', Decimal('3.96'), 'Cash'),
 (66, 55, datetime.datetime(2021, 10, 9, 0, 0), '421 Bourke Street', 'Sidney', 'NSW', 'Australia', '2010', Decimal('5.94'), 'Credit Card'),
 (67, 2, datetime.datetime(2021, 10, 12, 0, 0), 'Theodor-Heuss-Straße 34', 'Stuttgart', None, 'Germany', '70174', Decimal('8.91'), 'UPI'),
 (68, 11, datetime.datetime(2021, 10, 17, 0, 0), 'Av. Paulista, 2022', 'São Paulo', 'SP', 'Brazil', '01310-200', Decimal('13.86'), 'Cash'),
 (69, 25, datetime.datetime(2021, 10, 25, 0, 0), '319 N. Frances Street', 'Madison', 'WI', 'USA', '53703', Decimal('0.99'), 'Credit Card'),
 (70, 26, datetime.datetime(2021, 11, 7, 0, 0), '2211 W Berry Street', 'Fort Worth', 'TX', 'USA', '76110', Decimal('1.98'), 'UPI'),
 (71, 28, datetime.datetime(2021, 11, 7, 0, 0), '302 S 700 E', 'Salt Lake City', 'UT', 'USA', '84102', Decimal('1.98'), 'Cash'),
 (72, 30, datetime.datetime(2021, 11, 8, 0, 0), '230 Elgin Street', 'Ottawa', 'ON', 'Canada', 'K2P 1L7', Decimal('3.96'), 'Credit Card'),
 (73, 34, datetime.datetime(2021, 11, 9, 0, 0), 'Rua da Assunção 53', 'Lisbon', None, 'Portugal', None, Decimal('5.94'), 'UPI'),
 (74, 40, datetime.datetime(2021, 11, 12, 0, 0), '8, Rue Hanovre', 'Paris', None, 'France', '75002', Decimal('8.91'), 'Cash'),
 (75, 49, datetime.datetime(2021, 11, 17, 0, 0), 'Ordynacka 10', 'Warsaw', None, 'Poland', '00-358', Decimal('13.86'), 'Credit Card'),
 (76, 4, datetime.datetime(2021, 11, 25, 0, 0), 'Ullevålsveien 14', 'Oslo', None, 'Norway', '0171', Decimal('0.99'), 'UPI'),
 (77, 5, datetime.datetime(2021, 12, 8, 0, 0), 'Klanova 9/506', 'Prague', None, 'Czech Republic', '14700', Decimal('1.98'), 'Cash'),
 (78, 7, datetime.datetime(2021, 12, 8, 0, 0), 'Rotenturmstraße 4, 1010 Innere Stadt', 'Vienne', None, 'Austria', '1010', Decimal('1.98'), 'Credit Card'),
 (79, 9, datetime.datetime(2021, 12, 9, 0, 0), 'Sønder Boulevard 51', 'Copenhagen', None, 'Denmark', '1720', Decimal('3.96'), 'UPI'),
 (80, 13, datetime.datetime(2021, 12, 10, 0, 0), 'Qe 7 Bloco G', 'Brasília', 'DF', 'Brazil', '71020-677', Decimal('5.94'), 'Cash'),
 (81, 19, datetime.datetime(2021, 12, 13, 0, 0), '1 Infinite Loop', 'Cupertino', 'CA', 'USA', '95014', Decimal('8.91'), 'Credit Card'),
 (82, 28, datetime.datetime(2021, 12, 18, 0, 0), '302 S 700 E', 'Salt Lake City', 'UT', 'USA', '84102', Decimal('13.86'), 'UPI'),
 (83, 42, datetime.datetime(2021, 12, 26, 0, 0), '9, Place Louis Barthou', 'Bordeaux', None, 'France', '33000', Decimal('0.99'), 'Cash'),
 (84, 43, datetime.datetime(2022, 1, 8, 0, 0), '68, Rue Jouvence', 'Dijon', None, 'France', '21000', Decimal('1.98'), 'Credit Card'),
 (85, 45, datetime.datetime(2022, 1, 8, 0, 0), 'Erzsébet krt. 58.', 'Budapest', None, 'Hungary', 'H-1073', Decimal('1.98'), 'UPI'),
 (86, 47, datetime.datetime(2022, 1, 9, 0, 0), 'Via Degli Scipioni, 43', 'Rome', 'RM', 'Italy', '00192', Decimal('3.96'), 'Cash'),
 (87, 51, datetime.datetime(2022, 1, 10, 0, 0), 'Celsiusg. 9', 'Stockholm', None, 'Sweden', '11230', Decimal('6.94'), 'Credit Card'),
 (88, 57, datetime.datetime(2022, 1, 13, 0, 0), 'Calle Lira, 198', 'Santiago', None, 'Chile', None, Decimal('17.91'), 'UPI'),
 (89, 7, datetime.datetime(2022, 1, 18, 0, 0), 'Rotenturmstraße 4, 1010 Innere Stadt', 'Vienne', None, 'Austria', '1010', Decimal('18.86'), 'Cash'),
 (90, 21, datetime.datetime(2022, 1, 26, 0, 0), '801 W 4th Street', 'Reno', 'NV', 'USA', '89503', Decimal('0.99'), 'Credit Card'),
 (91, 22, datetime.datetime(2022, 2, 8, 0, 0), '120 S Orange Ave', 'Orlando', 'FL', 'USA', '32801', Decimal('1.98'), 'UPI'),
 (92, 24, datetime.datetime(2022, 2, 8, 0, 0), '162 E Superior Street', 'Chicago', 'IL', 'USA', '60611', Decimal('1.98'), 'Cash'),
 (93, 26, datetime.datetime(2022, 2, 9, 0, 0), '2211 W Berry Street', 'Fort Worth', 'TX', 'USA', '76110', Decimal('3.96'), 'Credit Card'),
 (94, 30, datetime.datetime(2022, 2, 10, 0, 0), '230 Elgin Street', 'Ottawa', 'ON', 'Canada', 'K2P 1L7', Decimal('5.94'), 'UPI'),
 (95, 36, datetime.datetime(2022, 2, 13, 0, 0), 'Tauentzienstraße 8', 'Berlin', None, 'Germany', '10789', Decimal('8.91'), 'Cash'),
 (96, 45, datetime.datetime(2022, 2, 18, 0, 0), 'Erzsébet krt. 58.', 'Budapest', None, 'Hungary', 'H-1073', Decimal('21.86'), 'Credit Card'),
 (97, 59, datetime.datetime(2022, 2, 26, 0, 0), '3,Raj Bhavan Road', 'Bangalore', None, 'India', '560001', Decimal('1.99'), 'UPI'),
 (98, 1, datetime.datetime(2022, 3, 11, 0, 0), 'Av. Brigadeiro Faria Lima, 2170', 'São José dos Campos', 'SP', 'Brazil', '12227-000', Decimal('3.98'), 'Cash'),
 (99, 3, datetime.datetime(2022, 3, 11, 0, 0), '1498 rue Bélanger', 'Montréal', 'QC', 'Canada', 'H2G 1A7', Decimal('3.98'), 'Credit Card'),
 (100, 5, datetime.datetime(2022, 3, 12, 0, 0), 'Klanova 9/506', 'Prague', None, 'Czech Republic', '14700', Decimal('3.96'), 'UPI'),
 (101, 9, datetime.datetime(2022, 3, 13, 0, 0), 'Sønder Boulevard 51', 'Copenhagen', None, 'Denmark', '1720', Decimal('5.94'), 'Cash'),
 (102, 15, datetime.datetime(2022, 3, 16, 0, 0), '700 W Pender Street', 'Vancouver', 'BC', 'Canada', 'V6C 1G8', Decimal('9.91'), 'Credit Card'),
 (103, 24, datetime.datetime(2022, 3, 21, 0, 0), '162 E Superior Street', 'Chicago', 'IL', 'USA', '60611', Decimal('15.86'), 'UPI'),
 (104, 38, datetime.datetime(2022, 3, 29, 0, 0), 'Barbarossastraße 19', 'Berlin', None, 'Germany', '10779', Decimal('0.99'), 'Cash'),
 (105, 39, datetime.datetime(2022, 4, 11, 0, 0), '4, Rue Milton', 'Paris', None, 'France', '75009', Decimal('1.98'), 'Credit Card'),
 (106, 41, datetime.datetime(2022, 4, 11, 0, 0), '11, Place Bellecour', 'Lyon', None, 'France', '69002', Decimal('1.98'), 'UPI'),
 (107, 43, datetime.datetime(2022, 4, 12, 0, 0), '68, Rue Jouvence', 'Dijon', None, 'France', '21000', Decimal('3.96'), 'Cash'),
 (108, 47, datetime.datetime(2022, 4, 13, 0, 0), 'Via Degli Scipioni, 43', 'Rome', 'RM', 'Italy', '00192', Decimal('5.94'), 'Credit Card'),
 (109, 53, datetime.datetime(2022, 4, 16, 0, 0), '113 Lupus St', 'London', None, 'United Kingdom', 'SW1V 3EN', Decimal('8.91'), 'UPI'),
 (110, 3, datetime.datetime(2022, 4, 21, 0, 0), '1498 rue Bélanger', 'Montréal', 'QC', 'Canada', 'H2G 1A7', Decimal('13.86'), 'Cash'),
 (111, 17, datetime.datetime(2022, 4, 29, 0, 0), '1 Microsoft Way', 'Redmond', 'WA', 'USA', '98052-8300', Decimal('0.99'), 'Credit Card'),
 (112, 18, datetime.datetime(2022, 5, 12, 0, 0), '627 Broadway', 'New York', 'NY', 'USA', '10012-2612', Decimal('1.98'), 'UPI'),
 (113, 20, datetime.datetime(2022, 5, 12, 0, 0), '541 Del Medio Avenue', 'Mountain View', 'CA', 'USA', '94040-111', Decimal('1.98'), 'Cash'),
 (114, 22, datetime.datetime(2022, 5, 13, 0, 0), '120 S Orange Ave', 'Orlando', 'FL', 'USA', '32801', Decimal('3.96'), 'Credit Card'),
 (115, 26, datetime.datetime(2022, 5, 14, 0, 0), '2211 W Berry Street', 'Fort Worth', 'TX', 'USA', '76110', Decimal('5.94'), 'UPI'),
 (116, 32, datetime.datetime(2022, 5, 17, 0, 0), '696 Osborne Street', 'Winnipeg', 'MB', 'Canada', 'R3L 2B9', Decimal('8.91'), 'Cash'),
 (117, 41, datetime.datetime(2022, 5, 22, 0, 0), '11, Place Bellecour', 'Lyon', None, 'France', '69002', Decimal('13.86'), 'Credit Card'),
 (118, 55, datetime.datetime(2022, 5, 30, 0, 0), '421 Bourke Street', 'Sidney', 'NSW', 'Australia', '2010', Decimal('0.99'), 'UPI'),
 (119, 56, datetime.datetime(2022, 6, 12, 0, 0), '307 Macacha Güemes', 'Buenos Aires', None, 'Argentina', '1106', Decimal('1.98'), 'Cash'),
 (120, 58, datetime.datetime(2022, 6, 12, 0, 0), '12,Community Centre', 'Delhi', None, 'India', '110017', Decimal('1.98'), 'Credit Card'),
 (121, 1, datetime.datetime(2022, 6, 13, 0, 0), 'Av. Brigadeiro Faria Lima, 2170', 'São José dos Campos', 'SP', 'Brazil', '12227-000', Decimal('3.96'), 'UPI'),
 (122, 5, datetime.datetime(2022, 6, 14, 0, 0), 'Klanova 9/506', 'Prague', None, 'Czech Republic', '14700', Decimal('5.94'), 'Cash'),
 (123, 11, datetime.datetime(2022, 6, 17, 0, 0), 'Av. Paulista, 2022', 'São Paulo', 'SP', 'Brazil', '01310-200', Decimal('8.91'), 'Credit Card'),
 (124, 20, datetime.datetime(2022, 6, 22, 0, 0), '541 Del Medio Avenue', 'Mountain View', 'CA', 'USA', '94040-111', Decimal('13.86'), 'UPI'),
 (125, 34, datetime.datetime(2022, 6, 30, 0, 0), 'Rua da Assunção 53', 'Lisbon', None, 'Portugal', None, Decimal('0.99'), 'Cash'),
 (126, 35, datetime.datetime(2022, 7, 13, 0, 0), 'Rua dos Campeões Europeus de Viena, 4350', 'Porto', None, 'Portugal', None, Decimal('1.98'), 'Credit Card'),
 (127, 37, datetime.datetime(2022, 7, 13, 0, 0), 'Berger Straße 10', 'Frankfurt', None, 'Germany', '60316', Decimal('1.98'), 'UPI'),
 (128, 39, datetime.datetime(2022, 7, 14, 0, 0), '4, Rue Milton', 'Paris', None, 'France', '75009', Decimal('3.96'), 'Cash'),
 (129, 43, datetime.datetime(2022, 7, 15, 0, 0), '68, Rue Jouvence', 'Dijon', None, 'France', '21000', Decimal('5.94'), 'Credit Card'),
 (130, 49, datetime.datetime(2022, 7, 18, 0, 0), 'Ordynacka 10', 'Warsaw', None, 'Poland', '00-358', Decimal('8.91'), 'UPI'),
 (131, 58, datetime.datetime(2022, 7, 23, 0, 0), '12,Community Centre', 'Delhi', None, 'India', '110017', Decimal('13.86'), 'Cash'),
 (132, 13, datetime.datetime(2022, 7, 31, 0, 0), 'Qe 7 Bloco G', 'Brasília', 'DF', 'Brazil', '71020-677', Decimal('0.99'), 'Credit Card'),
 (133, 14, datetime.datetime(2022, 8, 13, 0, 0), '8210 111 ST NW', 'Edmonton', 'AB', 'Canada', 'T6G 2C7', Decimal('1.98'), 'UPI'),
 (134, 16, datetime.datetime(2022, 8, 13, 0, 0), '1600 Amphitheatre Parkway', 'Mountain View', 'CA', 'USA', '94043-1351', Decimal('1.98'), 'Cash'),
 (135, 18, datetime.datetime(2022, 8, 14, 0, 0), '627 Broadway', 'New York', 'NY', 'USA', '10012-2612', Decimal('3.96'), 'Credit Card'),
 (136, 22, datetime.datetime(2022, 8, 15, 0, 0), '120 S Orange Ave', 'Orlando', 'FL', 'USA', '32801', Decimal('5.94'), 'UPI'),
 (137, 28, datetime.datetime(2022, 8, 18, 0, 0), '302 S 700 E', 'Salt Lake City', 'UT', 'USA', '84102', Decimal('8.91'), 'Cash'),
 (138, 37, datetime.datetime(2022, 8, 23, 0, 0), 'Berger Straße 10', 'Frankfurt', None, 'Germany', '60316', Decimal('13.86'), 'Credit Card'),
 (139, 51, datetime.datetime(2022, 8, 31, 0, 0), 'Celsiusg. 9', 'Stockholm', None, 'Sweden', '11230', Decimal('0.99'), 'UPI'),
 (140, 52, datetime.datetime(2022, 9, 13, 0, 0), '202 Hoxton Street', 'London', None, 'United Kingdom', 'N1 5LH', Decimal('1.98'), 'Cash'),
 (141, 54, datetime.datetime(2022, 9, 13, 0, 0), '110 Raeburn Pl', 'Edinburgh ', None, 'United Kingdom', 'EH4 1HH', Decimal('1.98'), 'Credit Card'),
 (142, 56, datetime.datetime(2022, 9, 14, 0, 0), '307 Macacha Güemes', 'Buenos Aires', None, 'Argentina', '1106', Decimal('3.96'), 'UPI'),
 (143, 1, datetime.datetime(2022, 9, 15, 0, 0), 'Av. Brigadeiro Faria Lima, 2170', 'São José dos Campos', 'SP', 'Brazil', '12227-000', Decimal('5.94'), 'Cash'),
 (144, 7, datetime.datetime(2022, 9, 18, 0, 0), 'Rotenturmstraße 4, 1010 Innere Stadt', 'Vienne', None, 'Austria', '1010', Decimal('8.91'), 'Credit Card'),
 (145, 16, datetime.datetime(2022, 9, 23, 0, 0), '1600 Amphitheatre Parkway', 'Mountain View', 'CA', 'USA', '94043-1351', Decimal('13.86'), 'UPI'),
 (146, 30, datetime.datetime(2022, 10, 1, 0, 0), '230 Elgin Street', 'Ottawa', 'ON', 'Canada', 'K2P 1L7', Decimal('0.99'), 'Cash'),
 (147, 31, datetime.datetime(2022, 10, 14, 0, 0), '194A Chain Lake Drive', 'Halifax', 'NS', 'Canada', 'B3S 1C5', Decimal('1.98'), 'Credit Card'),